orchestrator:
  file: '~/.orchestratorConfig'
  evals:
    - 0
    - 1
  toolregistries:
    - "dockstore"
  workflowservices:
    - "local"
toolregistries:
  file: './toolregistries.config'
  dockstore:
    host: "dockstore.org:8443"
    auth:
    proto: "https"
workflowservices:
  file: './workflowservices.config'
  local:
    host: "0.0.0.0:8080"
    auth:
    auth_type: ""
    proto: "http"
evals:
  file: './evals.config'
  wflow0:
    workflow_id: "github.com/dockstore-testing/md5sum-checker"
    version_id: "develop"
    trs_id: "dockstore"
    workflow_type: "CWL"
    submission_type: "params"
  wflow1:
    workflow_id: "github.com/dockstore-testing/md5sum-checker/wdl"
    version_id: "develop"
    trs_id: "dockstore"
    workflow_type: "WDL"
    submission_type: "params"
