language: python
python: 
  - '2.7'

before_install:
- sudo apt-get update -qq
- pip install toil[all]==3.16.0
- pip install . --process-dependency-links
- pip install -r dev-requirements.txt

script:
  - python setup.py test
  - flake8 --exclude wdl_parser.py --max-line-length 888 synorchestrator/

after_success:
  - coveralls
