language: python
python:
  - '3.6'

before_install:
- sudo apt-get update -qq
- pip install toil[cwl, wdl]
- pip install . --process-dependency-links
- pip install -r dev-requirements.txt

script:
  - python setup.py test
  - flake8 --ignore=E501,E722,F401,F841,W504 ga4ghtest/

after_success:
  - coveralls
