dist: bionic
language: python
python:
  - '3.6'

branches:
  only:
    - boconnor_issue_78

before_install:
- sudo apt-get update -qq
- pip install -r test-requirements.txt
- pip install -r requirements.txt .
- pip install --no-deps -r dev-requirements.txt

script:
  - python setup.py test
  # - flake8 --ignore=E501,E722,F401,F841,W504 ga4ghtest/

after_success:
  - coveralls
