queues:
  queue_1:
    trs_id: ''
    version_id: develop
    wes_default: local
    wes_opts:
    - local
    workflow_attachments:
    - file://tests/testdata/md5sum.input
    - file://tests/testdata/dockstore-tool-md5sum.cwl
    workflow_id: ''
    workflow_type: CWL
    workflow_url: file://tests/testdata/md5sum.cwl
  queue_2:
    trs_id: dockstore
    version_id: develop
    wes_default: local
    wes_opts:
    - local
    workflow_attachments:
    - !!python/unicode 'https://raw.githubusercontent.com/dockstore-testing/md5sum-checker/develop/md5sum/md5sum-tool.cwl'
    workflow_id: github.com/dockstore-testing/md5sum-checker
    workflow_type: CWL
    workflow_url: !!python/unicode 'https://raw.githubusercontent.com/dockstore-testing/md5sum-checker/develop/md5sum/md5sum-workflow.cwl'
  queue_2_checker:
    trs_id: dockstore
    version_id: develop
    wes_default: local
    wes_opts:
    - local
    workflow_attachments:
    - !!python/unicode 'https://raw.githubusercontent.com/dockstore-testing/md5sum-checker/develop/checker/md5sum-checker.cwl'
    - !!python/unicode 'https://raw.githubusercontent.com/dockstore-testing/md5sum-checker/develop/md5sum/md5sum-tool.cwl'
    - !!python/unicode 'https://raw.githubusercontent.com/dockstore-testing/md5sum-checker/develop/md5sum/md5sum-workflow.cwl'
    workflow_id: !!python/unicode 'github.com/dockstore-testing/md5sum-checker/_cwl_checker'
    workflow_type: CWL
    workflow_url: !!python/unicode 'https://raw.githubusercontent.com/dockstore-testing/md5sum-checker/develop/checker-workflow-wrapping-workflow.cwl'
toolregistries:
  dockstore:
    auth: ''
    auth_type: ''
    host: dockstore.org:8443
    proto: https
workflowservices:
  local:
    auth: ''
    auth_type: ''
    host: 0.0.0.0:8080
    proto: http
