queues:
  queue_1:
    trs_id: ''
    version_id: develop
    wes_default: local
    wes_opts:
    - local
    workflow_attachments:
    - file://tests/testdata/md5sum.input
    - file://tests/testdata/dockstore-tool-md5sum.cwl
    workflow_id: ''
    workflow_type: CWL
    workflow_url: file://tests/testdata/md5sum.cwl
toolregistries:
  dockstore:
    auth: ''
    auth_type: ''
    host: dockstore.org:8443
    proto: https
workflowservices:
  local:
    auth: ''
    auth_type: ''
    host: 0.0.0.0:8080
    proto: http
